import type { Prisma } from '@prisma/client';

export const PLAYER_DETAIL_STATS_SELECT = {
  matchesPlayed: true,
  minutesPlayed: true,
  goals: true,
  assists: true,
  yellowCards: true,
  redCards: true,
  dribblesAttempted: true,
  dribbleSuccessPct: true,
  progressiveCarries: true,
  carriesIntoFinalThird: true,
  ballRetentionPct: true,
  foulsWon: true,
  topSpeed: true,
  sprintDistance: true,
  accelerations: true,
  progressiveRuns: true,
  distanceCovered: true,
  passAccuracyPct: true,
  progressivePasses: true,
  keyPasses: true,
  throughBalls: true,
  crossAccuracyPct: true,
  xA: true,
  weakFootPassPct: true,
  weakFootPassAccuracyPct: true,
  progressiveWfPasses: true,
  goalsPer90: true,
  xGPer90: true,
  shotAccuracyPct: true,
  conversionRatePct: true,
  shotsOnTarget: true,
  touchesInBox: true,
  weakFootShotPct: true,
  weakFootGoals: true,
  weakFootShotAccuracyPct: true,
  tacklesWonPct: true,
  interceptions: true,
  recoveries: true,
  blocks: true,
  aerialDuelsWonPct: true,
  clearances: true,
  physicalDuelsWonPct: true,
  strengthDuels: true,
  balance: true,
  stamina: true,
  bodyContactSuccessPct: true,
} as const satisfies Prisma.PlayerSeasonStatsSelect;

export const PLAYER_DETAIL_SEASON_SELECT = {
  shirtNumber: true,
  contractStart: true,
  contractEnd: true,
  season: { select: { id: true, name: true, isCurrent: true } },
  club: {
    select: {
      id: true,
      name: true,
      shortName: true,
      league: true,
      country: true,
      logoUrl: true,
    },
  },
  activity: {
    select: { monthDate: true, minutesPlayed: true },
    orderBy: { monthDate: 'asc' as const },
  },
  stats: { select: PLAYER_DETAIL_STATS_SELECT },
} as const satisfies Prisma.PlayerSeasonSelect;

export const PLAYER_DETAIL_SELECT = {
  id: true,
  name: true,
  photoUrl: true,
  position: true,
  nationality: true,
  birthDate: true,
  height: true,
  weight: true,
  preferredFoot: true,
} as const satisfies Prisma.PlayerSelect;
