// prisma/seed.ts
import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import {
  PrismaClient,
  Position,
  PreferredFoot,
} from '../../generated/prisma/client';

const adapter = new PrismaPg(process.env.DATABASE_URL as string);
const prisma = new PrismaClient({ adapter });

async function main() {
  await prisma.player.deleteMany({});

  // ==================== SEASON (2023-2024) ====================
  const season = await prisma.season.upsert({
    where: { name: '2023-2024' },
    update: { isCurrent: true },
    create: {
      name: '2023-2024',
      startDate: new Date('2023-07-01'),
      endDate: new Date('2024-06-30'),
      isCurrent: true,
    },
  });

  // ==================== CLUB ====================
  const boca = await prisma.club.upsert({
    where: { name: 'Boca Juniors' },
    update: {},
    create: {
      name: 'Boca Juniors',
      shortName: 'BOCA',
      country: 'Argentina',
      league: 'Liga Profesional Argentina',
      logoUrl:
        'https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/5.png',
    },
  });

  // ==================== JUGADORES CON STATS COMPLETOS ====================
  const playersData = [
    {
      id: 'boca-merentiel-001',
      name: 'Miguel Merentiel',
      birthDate: new Date('1996-02-24'),
      nationality: 'Uruguay',
      position: Position.ST,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/40/37/554037_miguel_merentiel_20250616225234.png',
      height: 1.76,
      weight: 76,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 16,
      stats: {
        matchesPlayed: 38,
        minutesPlayed: 2650,
        goals: 14,
        assists: 5,
        yellowCards: 4,
        redCards: 0,
        dribblesAttempted: 98,
        dribbleSuccessPct: 57.1,
        progressiveCarries: 52,
        carriesIntoFinalThird: 38,
        ballRetentionPct: 71.3,
        foulsWon: 42,
        topSpeed: 32.8,
        sprintDistance: 1950,
        accelerations: 245,
        progressiveRuns: 78,
        distanceCovered: 9.1,
        passAccuracyPct: 76.4,
        progressivePasses: 41,
        keyPasses: 29,
        throughBalls: 6,
        crossAccuracyPct: 28,
        xA: 5.2,
        weakFootPassPct: 22,
        weakFootPassAccuracyPct: 61,
        goalsPer90: 0.48,
        xGPer90: 0.55,
        shotAccuracyPct: 55.8,
        conversionRatePct: 21.5,
        shotsOnTarget: 41,
        touchesInBox: 118,
        weakFootShotPct: 16,
        weakFootGoals: 3,
        weakFootShotAccuracyPct: 48,
        tacklesWonPct: 42,
        interceptions: 14,
        recoveries: 48,
        blocks: 9,
        aerialDuelsWonPct: 54,
        clearances: 12,
        physicalDuelsWonPct: 51.2,
        strengthDuels: 92,
        balance: 7.8,
        stamina: 7.2,
        bodyContactSuccessPct: 53,
        skillfulFootPassScore: 7.4,
        skillfulFootShotScore: 7.8,
      },
    },
    {
      id: 'boca-rojo-011',
      name: 'Marcos Rojo',
      birthDate: new Date('1990-03-20'),
      nationality: 'Argentina',
      position: Position.CB,
      photoUrl:
        'https://www.zerozero.com.ar/img/jogadores/new/28/91/92891_marcos_rojo_20250617001020.png',
      height: 1.87,
      weight: 80,
      preferredFoot: PreferredFoot.LEFT,
      shirtNumber: 6,
      stats: {
        matchesPlayed: 27,
        minutesPlayed: 2180,
        goals: 2,
        assists: 1,
        yellowCards: 8,
        redCards: 1,

        // Defending
        tacklesWonPct: 57,
        interceptions: 42,
        recoveries: 78,
        blocks: 35,
        aerialDuelsWonPct: 74,
        clearances: 92,

        // Physical
        physicalDuelsWonPct: 64,
        strengthDuels: 105,
        stamina: 7.3,

        // Passing
        passAccuracyPct: 85,
        progressivePasses: 38,

        // Otros
        skillfulFootPassScore: 7.5,
      },
    },
    {
      id: 'boca-cavani-002',
      name: 'Edinson Cavani',
      birthDate: new Date('1987-02-14'),
      nationality: 'Uruguay',
      position: Position.ST,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/46/05/1234605_edinson_cavani_20250121102300.png',
      height: 1.84,
      weight: 78,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 10,
      stats: {
        matchesPlayed: 32,
        minutesPlayed: 1980,
        goals: 11,
        assists: 4,
        yellowCards: 5,
        redCards: 1,
        dribblesAttempted: 64,
        dribbleSuccessPct: 51,
        progressiveCarries: 38,
        carriesIntoFinalThird: 25,
        ballRetentionPct: 68,
        foulsWon: 38,
        topSpeed: 31.2,
        sprintDistance: 1680,
        accelerations: 198,
        progressiveRuns: 55,
        distanceCovered: 8.4,
        passAccuracyPct: 74,
        progressivePasses: 32,
        keyPasses: 24,
        throughBalls: 8,
        crossAccuracyPct: 22,
        xA: 4.1,
        goalsPer90: 0.5,
        xGPer90: 0.58,
        shotAccuracyPct: 53,
        conversionRatePct: 24,
        shotsOnTarget: 36,
        touchesInBox: 95,
        weakFootShotPct: 28,
        weakFootGoals: 4,
        weakFootShotAccuracyPct: 52,
        aerialDuelsWonPct: 68,
        physicalDuelsWonPct: 58,
        strengthDuels: 85,
        skillfulFootPassScore: 7.1,
        skillfulFootShotScore: 7.9,
      },
    },
    {
      id: 'boca-zenon-003',
      name: 'Kevin Zenón',
      birthDate: new Date('2001-07-17'),
      nationality: 'Argentina',
      position: Position.LM,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/39/88/833988_kevin_zenon_20250616225026.png',
      height: 1.82,
      weight: 74,
      preferredFoot: PreferredFoot.LEFT,
      shirtNumber: 22,
      stats: {
        matchesPlayed: 35,
        minutesPlayed: 2480,
        goals: 6,
        assists: 8,
        yellowCards: 3,
        redCards: 0,
        dribblesAttempted: 112,
        dribbleSuccessPct: 62,
        progressiveCarries: 68,
        carriesIntoFinalThird: 55,
        ballRetentionPct: 78.5,
        foulsWon: 51,
        topSpeed: 33.1,
        sprintDistance: 2100,
        accelerations: 280,
        progressiveRuns: 72,
        passAccuracyPct: 83.2,
        progressivePasses: 58,
        keyPasses: 52,
        throughBalls: 12,
        crossAccuracyPct: 36,
        xA: 7.8,
        goalsPer90: 0.22,
        xGPer90: 0.28,
        shotAccuracyPct: 48,
        tacklesWonPct: 48,
        interceptions: 28,
        recoveries: 72,
        physicalDuelsWonPct: 49,
        stamina: 8.1,
        skillfulFootPassScore: 8.4,
        skillfulFootShotScore: 7.3,
      },
    },
    {
      id: 'boca-medina-004',
      name: 'Cristian Medina',
      birthDate: new Date('2002-05-26'),
      nationality: 'Argentina',
      position: Position.CM,
      photoUrl:
        'https://cdn.fifacm.com/content/media/imgs/fc24/players/p261082.png?v=26',
      height: 1.76,
      weight: 72,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 8,
      stats: {
        matchesPlayed: 36,
        minutesPlayed: 2720,
        goals: 3,
        assists: 5,
        yellowCards: 6,
        redCards: 0,
        dribblesAttempted: 68,
        dribbleSuccessPct: 54,
        passAccuracyPct: 86.5,
        progressivePasses: 62,
        keyPasses: 38,
        throughBalls: 9,
        tacklesWonPct: 55,
        interceptions: 45,
        recoveries: 98,
        blocks: 18,
        physicalDuelsWonPct: 52,
        stamina: 8.4,
        skillfulFootPassScore: 8.1,
        skillfulFootShotScore: 6.8,
      },
    },
    {
      id: 'boca-figal-005',
      name: 'Nicolás Figal',
      birthDate: new Date('1994-07-03'),
      nationality: 'Argentina',
      position: Position.CB,
      photoUrl:
        'https://www.zerozero.com.ar/img/jogadores/new/59/09/415909_nicolas_figal_20250616225820.png',
      height: 1.8,
      weight: 76,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 4,
      stats: {
        matchesPlayed: 30,
        minutesPlayed: 2450,
        goals: 1,
        assists: 2,
        yellowCards: 7,
        redCards: 1,
        aerialDuelsWonPct: 71,
        clearances: 78,
        blocks: 32,
        interceptions: 48,
        tacklesWonPct: 59,
        recoveries: 85,
        physicalDuelsWonPct: 62,
        strengthDuels: 95,
        stamina: 7.5,
        passAccuracyPct: 88,
      },
    },
    {
      id: 'boca-blanco-006',
      name: 'Lautaro Blanco',
      birthDate: new Date('1999-02-22'),
      nationality: 'Argentina',
      position: Position.LB,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/49/96/834996_lautaro_blanco_20250616225912.png',
      height: 1.83,
      weight: 73,
      preferredFoot: PreferredFoot.LEFT,
      shirtNumber: 3,
      stats: {
        matchesPlayed: 28,
        minutesPlayed: 2100,
        goals: 2,
        assists: 4,
        yellowCards: 5,
        progressiveCarries: 55,
        crossAccuracyPct: 32,
        tacklesWonPct: 52,
        interceptions: 35,
        recoveries: 68,
        passAccuracyPct: 81,
        skillfulFootPassScore: 7.6,
      },
    },
    {
      id: 'boca-zeballos-008',
      name: 'Exequiel Zeballos',
      birthDate: new Date('2002-04-24'),
      nationality: 'Argentina',
      position: Position.RW,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/77/49/707749_exequiel_zeballos_20250617004001.png',
      height: 1.73,
      weight: 68,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 7,
      stats: {
        matchesPlayed: 29,
        minutesPlayed: 1680,
        goals: 5,
        assists: 6,
        yellowCards: 4,
        dribblesAttempted: 125,
        dribbleSuccessPct: 65,
        progressiveCarries: 72,
        keyPasses: 35,
        crossAccuracyPct: 29,
        skillfulFootPassScore: 7.5,
        skillfulFootShotScore: 7.2,
      },
    },
    {
      id: 'boca-advincula-009',
      name: 'Luis Advíncula',
      birthDate: new Date('1990-03-02'),
      nationality: 'Perú',
      position: Position.RB,
      photoUrl:
        'https://www.zerozero.com.ar/img/jogadores/new/52/37/85237_luis_advincula_20250616225503.png',
      height: 1.8,
      weight: 78,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 17,
      stats: {
        matchesPlayed: 31,
        minutesPlayed: 2580,
        goals: 1,
        assists: 3,
        yellowCards: 6,
        progressiveCarries: 48,
        tacklesWonPct: 54,
        interceptions: 42,
        recoveries: 78,
        stamina: 8.3,
      },
    },
    {
      id: 'boca-fabra-010',
      name: 'Frank Fabra',
      birthDate: new Date('1991-02-22'),
      nationality: 'Colombia',
      position: Position.LB,
      photoUrl:
        'https://www.zerozero.com.ar/img/jogadores/new/99/94/179994_frank_fabra_20250617000800.png',
      height: 1.75,
      weight: 72,
      preferredFoot: PreferredFoot.LEFT,
      shirtNumber: 18,
      stats: {
        matchesPlayed: 26,
        minutesPlayed: 1980,
        goals: 1,
        assists: 4,
        yellowCards: 6,
        crossAccuracyPct: 33,
        progressiveCarries: 45,
        tacklesWonPct: 50,
      },
    },
  ];

  for (const p of playersData) {
    const player = await prisma.player.upsert({
      where: { id: p.id },
      update: {},
      create: {
        id: p.id,
        name: p.name,
        birthDate: p.birthDate,
        nationality: p.nationality,
        position: p.position,
        photoUrl: p.photoUrl,
        height: p.height,
        weight: p.weight,
        preferredFoot: p.preferredFoot,
      },
    });

    const playerSeason = await prisma.playerSeason.upsert({
      where: {
        playerId_seasonId: { playerId: player.id, seasonId: season.id },
      },
      update: {},
      create: {
        playerId: player.id,
        seasonId: season.id,
        clubId: boca.id,
        shirtNumber: p.shirtNumber,
        contractStart: new Date('2023-07-01'),
        contractEnd: new Date('2024-06-30'),
        stats: { create: p.stats },
      },
    });

    await prisma.playerActivity.createMany({
      data: [
        '2023-08-01',
        '2023-09-01',
        '2023-10-01',
        '2023-11-01',
        '2023-12-01',
        '2024-01-01',
        '2024-02-01',
        '2024-03-01',
        '2024-04-01',
        '2024-05-01',
      ].map((month) => ({
        playerSeasonId: playerSeason.id,
        monthDate: new Date(month),
        minutesPlayed: 180 + Math.floor(Math.random() * 160),
      })),
      skipDuplicates: true,
    });
  }

  console.log(
    '✅ Seed completado - 10 jugadores con stats completos (Temporada 2023-2024)',
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => await prisma.$disconnect());
