// prisma/seed.ts
import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import {
  PrismaClient,
  Position,
  PreferredFoot,
} from '../../generated/prisma/client';

const adapter = new PrismaPg(process.env.DATABASE_URL as string);
const prisma = new PrismaClient({ adapter });

function withCardFrequencies<
  T extends { matchesPlayed: number; yellowCards: number; redCards: number },
>(
  stats: T,
): T & {
  matchesPerYellowCard: number | null;
  matchesPerRedCard: number | null;
} {
  return {
    ...stats,
    matchesPerYellowCard:
      stats.matchesPlayed > 0 && stats.yellowCards > 0
        ? stats.matchesPlayed / stats.yellowCards
        : null,
    matchesPerRedCard:
      stats.matchesPlayed > 0 && stats.redCards > 0
        ? stats.matchesPlayed / stats.redCards
        : null,
  };
}

async function main() {
  await prisma.player.deleteMany({});

  // ==================== SEASON (2023-2024) ====================
  const season = await prisma.season.upsert({
    where: { name: '2023-2024' },
    update: { isCurrent: true },
    create: {
      name: '2023-2024',
      startDate: new Date('2023-07-01'),
      endDate: new Date('2024-06-30'),
      isCurrent: true,
    },
  });

  // ==================== CLUB ====================
  const bocaClub = {
    name: 'Boca Juniors',
    shortName: 'BOCA',
    country: 'Argentina',
    league: 'Liga Profesional Argentina',
    logoUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Boca_Juniors_logo18.svg/500px-Boca_Juniors_logo18.svg.png',
  };
  const boca = await prisma.club.upsert({
    where: { name: bocaClub.name },
    update: {
      shortName: bocaClub.shortName,
      country: bocaClub.country,
      league: bocaClub.league,
      logoUrl: bocaClub.logoUrl,
    },
    create: bocaClub,
  });

  const riverClub = {
    name: 'Club Atlético River Plate',
    shortName: 'RIVER',
    country: 'Argentina',
    league: 'Liga Profesional Argentina',
    logoUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Club_Atl%C3%A9tico_River_Plate_logo.svg/250px-Club_Atl%C3%A9tico_River_Plate_logo.svg.png',
  };
  const river = await prisma.club.upsert({
    where: { name: riverClub.name },
    update: {
      shortName: riverClub.shortName,
      country: riverClub.country,
      league: riverClub.league,
      logoUrl: riverClub.logoUrl,
    },
    create: riverClub,
  });

  const barcelonaClub = {
    name: 'FC Barcelona',
    shortName: 'FCB',
    country: 'Spain',
    league: 'La Liga',
    logoUrl:
      'https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/500px-FC_Barcelona_%28crest%29.svg.png',
  };
  const barcelona = await prisma.club.upsert({
    where: { name: barcelonaClub.name },
    update: {
      shortName: barcelonaClub.shortName,
      country: barcelonaClub.country,
      league: barcelonaClub.league,
      logoUrl: barcelonaClub.logoUrl,
    },
    create: barcelonaClub,
  });

  const realMadridClub = {
    name: 'Real Madrid CF',
    shortName: 'RMA',
    country: 'Spain',
    league: 'La Liga',
    logoUrl:
      'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/500px-Real_Madrid_CF.svg.png',
  };
  const realMadrid = await prisma.club.upsert({
    where: { name: realMadridClub.name },
    update: {
      shortName: realMadridClub.shortName,
      country: realMadridClub.country,
      league: realMadridClub.league,
      logoUrl: realMadridClub.logoUrl,
    },
    create: realMadridClub,
  });

  const clubs = { boca, river, barcelona, realMadrid };

  const playersSeed = [
    {
      clubKey: 'boca' as const,
      id: 'boca-merentiel-001',
      name: 'Miguel Merentiel',
      birthDate: new Date('1996-02-24'),
      nationality: 'Uruguay',
      position: Position.ST,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/40/37/554037_miguel_merentiel_20250616225234.png',
      height: 1.76,
      weight: 76,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 16,
      contractStart: new Date('2023-02-14'),
      contractEnd: new Date('2027-12-31'),
      stats: {
        matchesPlayed: 38,
        minutesPlayed: 2650,
        goals: 14,
        assists: 5,
        yellowCards: 4,
        redCards: 0,
        dribblesAttempted: 98,
        dribbleSuccessPct: 57.1,
        progressiveCarries: 52,
        carriesIntoFinalThird: 38,
        ballRetentionPct: 71.3,
        foulsWon: 42,
        topSpeed: 32.8,
        sprintDistance: 1950,
        accelerations: 245,
        progressiveRuns: 78,
        distanceCovered: 9.1,
        passAccuracyPct: 76.4,
        progressivePasses: 41,
        keyPasses: 29,
        throughBalls: 6,
        crossAccuracyPct: 28,
        xA: 5.2,
        weakFootPassPct: 22,
        weakFootPassAccuracyPct: 61,
        progressiveWfPasses: 19,
        skillfulFootPassScore: 7.4,
        goalsPer90: 0.48,
        xGPer90: 0.55,
        shotAccuracyPct: 55.8,
        conversionRatePct: 21.5,
        shotsOnTarget: 41,
        touchesInBox: 118,
        weakFootShotPct: 16,
        weakFootGoals: 3,
        weakFootShotAccuracyPct: 48,
        skillfulFootShotScore: 7.8,
        tacklesWonPct: 42,
        interceptions: 14,
        recoveries: 48,
        blocks: 9,
        aerialDuelsWonPct: 54,
        clearances: 12,
        physicalDuelsWonPct: 51.2,
        strengthDuels: 92,
        balance: 7.8,
        stamina: 7.2,
        bodyContactSuccessPct: 53,
      },
    },
    {
      clubKey: 'boca' as const,
      id: 'boca-rojo-011',
      name: 'Marcos Rojo',
      birthDate: new Date('1990-03-20'),
      nationality: 'Argentina',
      position: Position.CB,
      photoUrl:
        'https://www.zerozero.com.ar/img/jogadores/new/28/91/92891_marcos_rojo_20250617001020.png',
      height: 1.87,
      weight: 80,
      preferredFoot: PreferredFoot.LEFT,
      shirtNumber: 6,
      contractStart: new Date('2023-08-25'),
      contractEnd: new Date('2025-12-31'),
      stats: {
        matchesPlayed: 27,
        minutesPlayed: 2180,
        goals: 2,
        assists: 1,
        yellowCards: 8,
        redCards: 1,
        dribblesAttempted: 24,
        dribbleSuccessPct: 46,
        progressiveCarries: 19,
        carriesIntoFinalThird: 9,
        ballRetentionPct: 82.5,
        foulsWon: 14,
        topSpeed: 28.6,
        sprintDistance: 1140,
        accelerations: 98,
        progressiveRuns: 16,
        distanceCovered: 7.85,
        passAccuracyPct: 85,
        progressivePasses: 38,
        keyPasses: 9,
        throughBalls: 2,
        crossAccuracyPct: 19,
        xA: 0.45,
        weakFootPassPct: 34,
        weakFootPassAccuracyPct: 71,
        progressiveWfPasses: 11,
        skillfulFootPassScore: 7.5,
        goalsPer90: 0.08,
        xGPer90: 0.07,
        shotAccuracyPct: 41,
        conversionRatePct: 14,
        shotsOnTarget: 9,
        touchesInBox: 48,
        weakFootShotPct: 22,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 36,
        skillfulFootShotScore: 6.6,
        tacklesWonPct: 57,
        interceptions: 42,
        recoveries: 78,
        blocks: 35,
        aerialDuelsWonPct: 74,
        clearances: 92,
        physicalDuelsWonPct: 64,
        strengthDuels: 105,
        balance: 6.9,
        stamina: 7.3,
        bodyContactSuccessPct: 61,
      },
    },
    {
      clubKey: 'boca' as const,
      id: 'boca-cavani-002',
      name: 'Edinson Cavani',
      birthDate: new Date('1987-02-14'),
      nationality: 'Uruguay',
      position: Position.ST,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/46/05/1234605_edinson_cavani_20250121102300.png',
      height: 1.84,
      weight: 78,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 10,
      contractStart: new Date('2023-07-24'),
      contractEnd: new Date('2026-12-31'),
      stats: {
        matchesPlayed: 32,
        minutesPlayed: 1980,
        goals: 11,
        assists: 4,
        yellowCards: 5,
        redCards: 1,
        dribblesAttempted: 64,
        dribbleSuccessPct: 51,
        progressiveCarries: 38,
        carriesIntoFinalThird: 25,
        ballRetentionPct: 68,
        foulsWon: 38,
        topSpeed: 31.2,
        sprintDistance: 1680,
        accelerations: 198,
        progressiveRuns: 55,
        distanceCovered: 8.4,
        passAccuracyPct: 74,
        progressivePasses: 32,
        keyPasses: 24,
        throughBalls: 8,
        crossAccuracyPct: 22,
        xA: 4.1,
        weakFootPassPct: 25,
        weakFootPassAccuracyPct: 68,
        progressiveWfPasses: 21,
        skillfulFootPassScore: 7.1,
        goalsPer90: 0.5,
        xGPer90: 0.58,
        shotAccuracyPct: 53,
        conversionRatePct: 24,
        shotsOnTarget: 36,
        touchesInBox: 95,
        weakFootShotPct: 28,
        weakFootGoals: 4,
        weakFootShotAccuracyPct: 52,
        skillfulFootShotScore: 7.9,
        tacklesWonPct: 36,
        interceptions: 12,
        recoveries: 42,
        blocks: 8,
        aerialDuelsWonPct: 68,
        clearances: 18,
        physicalDuelsWonPct: 58,
        strengthDuels: 85,
        balance: 7.5,
        stamina: 7,
        bodyContactSuccessPct: 58,
      },
    },
    {
      clubKey: 'boca' as const,
      id: 'boca-zenon-003',
      name: 'Kevin Zenón',
      birthDate: new Date('2001-07-17'),
      nationality: 'Argentina',
      position: Position.LM,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/39/88/833988_kevin_zenon_20250616225026.png',
      height: 1.82,
      weight: 74,
      preferredFoot: PreferredFoot.LEFT,
      shirtNumber: 22,
      contractStart: new Date('2023-01-12'),
      contractEnd: new Date('2028-12-31'),
      stats: {
        matchesPlayed: 35,
        minutesPlayed: 2480,
        goals: 6,
        assists: 8,
        yellowCards: 3,
        redCards: 0,
        dribblesAttempted: 112,
        dribbleSuccessPct: 62,
        progressiveCarries: 68,
        carriesIntoFinalThird: 55,
        ballRetentionPct: 78.5,
        foulsWon: 51,
        topSpeed: 33.1,
        sprintDistance: 2100,
        accelerations: 280,
        progressiveRuns: 72,
        distanceCovered: 9.6,
        passAccuracyPct: 83.2,
        progressivePasses: 58,
        keyPasses: 52,
        throughBalls: 12,
        crossAccuracyPct: 36,
        xA: 7.8,
        weakFootPassPct: 28,
        weakFootPassAccuracyPct: 74,
        progressiveWfPasses: 26,
        skillfulFootPassScore: 8.4,
        goalsPer90: 0.22,
        xGPer90: 0.28,
        shotAccuracyPct: 48,
        conversionRatePct: 17,
        shotsOnTarget: 28,
        touchesInBox: 72,
        weakFootShotPct: 20,
        weakFootGoals: 1,
        weakFootShotAccuracyPct: 42,
        skillfulFootShotScore: 7.3,
        tacklesWonPct: 48,
        interceptions: 28,
        recoveries: 72,
        blocks: 14,
        aerialDuelsWonPct: 44,
        clearances: 22,
        physicalDuelsWonPct: 49,
        strengthDuels: 76,
        balance: 8,
        stamina: 8.1,
        bodyContactSuccessPct: 47,
      },
    },
    {
      clubKey: 'boca' as const,
      id: 'boca-medina-004',
      name: 'Cristian Medina',
      birthDate: new Date('2002-05-26'),
      nationality: 'Argentina',
      position: Position.CM,
      photoUrl:
        'https://cdn.fifacm.com/content/media/imgs/fc24/players/p261082.png?v=26',
      height: 1.76,
      weight: 72,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 8,
      contractStart: new Date('2022-06-30'),
      contractEnd: new Date('2028-06-30'),
      stats: {
        matchesPlayed: 36,
        minutesPlayed: 2720,
        goals: 3,
        assists: 5,
        yellowCards: 6,
        redCards: 0,
        dribblesAttempted: 68,
        dribbleSuccessPct: 54,
        progressiveCarries: 48,
        carriesIntoFinalThird: 34,
        ballRetentionPct: 84,
        foulsWon: 28,
        topSpeed: 30.4,
        sprintDistance: 1520,
        accelerations: 188,
        progressiveRuns: 44,
        distanceCovered: 10.2,
        passAccuracyPct: 86.5,
        progressivePasses: 62,
        keyPasses: 38,
        throughBalls: 9,
        crossAccuracyPct: 31,
        xA: 4.6,
        weakFootPassPct: 24,
        weakFootPassAccuracyPct: 79,
        progressiveWfPasses: 24,
        skillfulFootPassScore: 8.1,
        goalsPer90: 0.1,
        xGPer90: 0.08,
        shotAccuracyPct: 44,
        conversionRatePct: 12,
        shotsOnTarget: 12,
        touchesInBox: 38,
        weakFootShotPct: 18,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 38,
        skillfulFootShotScore: 6.8,
        tacklesWonPct: 55,
        interceptions: 45,
        recoveries: 98,
        blocks: 18,
        aerialDuelsWonPct: 46,
        clearances: 28,
        physicalDuelsWonPct: 52,
        strengthDuels: 88,
        balance: 7.6,
        stamina: 8.4,
        bodyContactSuccessPct: 51,
      },
    },
    {
      clubKey: 'boca' as const,
      id: 'boca-figal-005',
      name: 'Nicolás Figal',
      birthDate: new Date('1994-07-03'),
      nationality: 'Argentina',
      position: Position.CB,
      photoUrl:
        'https://www.zerozero.com.ar/img/jogadores/new/59/09/415909_nicolas_figal_20250616225820.png',
      height: 1.8,
      weight: 76,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 4,
      contractStart: new Date('2022-01-26'),
      contractEnd: new Date('2027-12-31'),
      stats: {
        matchesPlayed: 30,
        minutesPlayed: 2450,
        goals: 1,
        assists: 2,
        yellowCards: 7,
        redCards: 1,
        dribblesAttempted: 26,
        dribbleSuccessPct: 52,
        progressiveCarries: 22,
        carriesIntoFinalThird: 10,
        ballRetentionPct: 83,
        foulsWon: 16,
        topSpeed: 29.2,
        sprintDistance: 1200,
        accelerations: 108,
        progressiveRuns: 18,
        distanceCovered: 8.1,
        passAccuracyPct: 88,
        progressivePasses: 52,
        keyPasses: 11,
        throughBalls: 3,
        crossAccuracyPct: 16,
        xA: 0.55,
        weakFootPassPct: 20,
        weakFootPassAccuracyPct: 69,
        progressiveWfPasses: 15,
        skillfulFootPassScore: 7.2,
        goalsPer90: 0.04,
        xGPer90: 0.05,
        shotAccuracyPct: 33,
        conversionRatePct: 10,
        shotsOnTarget: 5,
        touchesInBox: 35,
        weakFootShotPct: 15,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 30,
        skillfulFootShotScore: 6.2,
        tacklesWonPct: 59,
        interceptions: 48,
        recoveries: 85,
        blocks: 32,
        aerialDuelsWonPct: 71,
        clearances: 78,
        physicalDuelsWonPct: 62,
        strengthDuels: 95,
        balance: 7,
        stamina: 7.5,
        bodyContactSuccessPct: 59,
      },
    },
    {
      clubKey: 'boca' as const,
      id: 'boca-blanco-006',
      name: 'Lautaro Blanco',
      birthDate: new Date('1999-02-22'),
      nationality: 'Argentina',
      position: Position.LB,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/49/96/834996_lautaro_blanco_20250616225912.png',
      height: 1.83,
      weight: 73,
      preferredFoot: PreferredFoot.LEFT,
      shirtNumber: 3,
      contractStart: new Date('2023-07-01'),
      contractEnd: new Date('2026-12-31'),
      stats: {
        matchesPlayed: 28,
        minutesPlayed: 2100,
        goals: 2,
        assists: 4,
        yellowCards: 5,
        redCards: 0,
        dribblesAttempted: 58,
        dribbleSuccessPct: 55,
        progressiveCarries: 55,
        carriesIntoFinalThird: 42,
        ballRetentionPct: 79,
        foulsWon: 32,
        topSpeed: 32.4,
        sprintDistance: 1860,
        accelerations: 226,
        progressiveRuns: 58,
        distanceCovered: 9.35,
        passAccuracyPct: 81,
        progressivePasses: 44,
        keyPasses: 28,
        throughBalls: 5,
        crossAccuracyPct: 32,
        xA: 4.2,
        weakFootPassPct: 26,
        weakFootPassAccuracyPct: 73,
        progressiveWfPasses: 18,
        skillfulFootPassScore: 7.6,
        goalsPer90: 0.09,
        xGPer90: 0.07,
        shotAccuracyPct: 40,
        conversionRatePct: 15,
        shotsOnTarget: 8,
        touchesInBox: 42,
        weakFootShotPct: 18,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 35,
        skillfulFootShotScore: 6.5,
        tacklesWonPct: 52,
        interceptions: 35,
        recoveries: 68,
        blocks: 24,
        aerialDuelsWonPct: 52,
        clearances: 55,
        physicalDuelsWonPct: 54,
        strengthDuels: 82,
        balance: 7.4,
        stamina: 8,
        bodyContactSuccessPct: 52,
      },
    },
    {
      clubKey: 'boca' as const,
      id: 'boca-zeballos-008',
      name: 'Exequiel Zeballos',
      birthDate: new Date('2002-04-24'),
      nationality: 'Argentina',
      position: Position.RW,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/77/49/707749_exequiel_zeballos_20250617004001.png',
      height: 1.73,
      weight: 68,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 7,
      contractStart: new Date('2021-03-20'),
      contractEnd: new Date('2028-12-31'),
      stats: {
        matchesPlayed: 29,
        minutesPlayed: 1680,
        goals: 5,
        assists: 6,
        yellowCards: 4,
        redCards: 0,
        dribblesAttempted: 125,
        dribbleSuccessPct: 65,
        progressiveCarries: 72,
        carriesIntoFinalThird: 61,
        ballRetentionPct: 76,
        foulsWon: 56,
        topSpeed: 33.6,
        sprintDistance: 2240,
        accelerations: 302,
        progressiveRuns: 81,
        distanceCovered: 8.85,
        passAccuracyPct: 78.5,
        progressivePasses: 41,
        keyPasses: 35,
        throughBalls: 10,
        crossAccuracyPct: 29,
        xA: 5.8,
        weakFootPassPct: 22,
        weakFootPassAccuracyPct: 67,
        progressiveWfPasses: 20,
        skillfulFootPassScore: 7.5,
        goalsPer90: 0.27,
        xGPer90: 0.32,
        shotAccuracyPct: 51,
        conversionRatePct: 19,
        shotsOnTarget: 22,
        touchesInBox: 88,
        weakFootShotPct: 14,
        weakFootGoals: 1,
        weakFootShotAccuracyPct: 45,
        skillfulFootShotScore: 7.2,
        tacklesWonPct: 38,
        interceptions: 18,
        recoveries: 52,
        blocks: 8,
        aerialDuelsWonPct: 38,
        clearances: 12,
        physicalDuelsWonPct: 43,
        strengthDuels: 64,
        balance: 8.3,
        stamina: 7.6,
        bodyContactSuccessPct: 44,
      },
    },
    {
      clubKey: 'boca' as const,
      id: 'boca-advincula-009',
      name: 'Luis Advíncula',
      birthDate: new Date('1990-03-02'),
      nationality: 'Perú',
      position: Position.RB,
      photoUrl:
        'https://www.zerozero.com.ar/img/jogadores/new/52/37/85237_luis_advincula_20250616225503.png',
      height: 1.8,
      weight: 78,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 17,
      contractStart: new Date('2021-07-21'),
      contractEnd: new Date('2026-12-31'),
      stats: {
        matchesPlayed: 31,
        minutesPlayed: 2580,
        goals: 1,
        assists: 3,
        yellowCards: 6,
        redCards: 0,
        dribblesAttempted: 72,
        dribbleSuccessPct: 58,
        progressiveCarries: 48,
        carriesIntoFinalThird: 36,
        ballRetentionPct: 77,
        foulsWon: 24,
        topSpeed: 34.8,
        sprintDistance: 2420,
        accelerations: 268,
        progressiveRuns: 62,
        distanceCovered: 10.35,
        passAccuracyPct: 79,
        progressivePasses: 35,
        keyPasses: 18,
        throughBalls: 4,
        crossAccuracyPct: 27,
        xA: 3.4,
        weakFootPassPct: 18,
        weakFootPassAccuracyPct: 66,
        progressiveWfPasses: 12,
        skillfulFootPassScore: 7,
        goalsPer90: 0.035,
        xGPer90: 0.04,
        shotAccuracyPct: 36,
        conversionRatePct: 9,
        shotsOnTarget: 6,
        touchesInBox: 28,
        weakFootShotPct: 12,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 28,
        skillfulFootShotScore: 6.1,
        tacklesWonPct: 54,
        interceptions: 42,
        recoveries: 78,
        blocks: 26,
        aerialDuelsWonPct: 48,
        clearances: 48,
        physicalDuelsWonPct: 58,
        strengthDuels: 94,
        balance: 7.2,
        stamina: 8.3,
        bodyContactSuccessPct: 56,
      },
    },
    {
      clubKey: 'boca' as const,
      id: 'boca-fabra-010',
      name: 'Frank Fabra',
      birthDate: new Date('1991-02-22'),
      nationality: 'Colombia',
      position: Position.LB,
      photoUrl:
        'https://www.zerozero.com.ar/img/jogadores/new/99/94/179994_frank_fabra_20250617000800.png',
      height: 1.75,
      weight: 72,
      preferredFoot: PreferredFoot.LEFT,
      shirtNumber: 18,
      contractStart: new Date('2022-01-01'),
      contractEnd: new Date('2025-12-31'),
      stats: {
        matchesPlayed: 26,
        minutesPlayed: 1980,
        goals: 1,
        assists: 4,
        yellowCards: 6,
        redCards: 0,
        dribblesAttempted: 46,
        dribbleSuccessPct: 52,
        progressiveCarries: 45,
        carriesIntoFinalThird: 38,
        ballRetentionPct: 78,
        foulsWon: 30,
        topSpeed: 31.8,
        sprintDistance: 1760,
        accelerations: 208,
        progressiveRuns: 52,
        distanceCovered: 9.05,
        passAccuracyPct: 82,
        progressivePasses: 39,
        keyPasses: 26,
        throughBalls: 5,
        crossAccuracyPct: 33,
        xA: 4.4,
        weakFootPassPct: 24,
        weakFootPassAccuracyPct: 70,
        progressiveWfPasses: 17,
        skillfulFootPassScore: 7.7,
        goalsPer90: 0.045,
        xGPer90: 0.06,
        shotAccuracyPct: 38,
        conversionRatePct: 11,
        shotsOnTarget: 5,
        touchesInBox: 34,
        weakFootShotPct: 16,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 32,
        skillfulFootShotScore: 6.6,
        tacklesWonPct: 50,
        interceptions: 32,
        recoveries: 62,
        blocks: 22,
        aerialDuelsWonPct: 50,
        clearances: 44,
        physicalDuelsWonPct: 55,
        strengthDuels: 78,
        balance: 7.3,
        stamina: 7.8,
        bodyContactSuccessPct: 54,
      },
    },
    {
      clubKey: 'river' as const,
      id: 'river-casco-002',
      name: 'Milton Casco',
      birthDate: new Date('1988-12-11'),
      nationality: 'Argentina',
      position: Position.RB,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/00/99/100099_milton_casco_20250618092550.png',
      height: 1.67,
      weight: 68,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 20,
      contractStart: new Date('2017-01-01'),
      contractEnd: new Date('2025-12-31'),
      stats: {
        matchesPlayed: 32,
        minutesPlayed: 2680,
        goals: 2,
        assists: 6,
        yellowCards: 7,
        redCards: 0,
        dribblesAttempted: 62,
        dribbleSuccessPct: 54,
        progressiveCarries: 58,
        carriesIntoFinalThird: 48,
        ballRetentionPct: 79,
        foulsWon: 34,
        topSpeed: 31.2,
        sprintDistance: 1780,
        accelerations: 198,
        progressiveRuns: 55,
        distanceCovered: 9.55,
        passAccuracyPct: 84,
        progressivePasses: 42,
        keyPasses: 32,
        throughBalls: 4,
        crossAccuracyPct: 34,
        xA: 5.1,
        weakFootPassPct: 22,
        weakFootPassAccuracyPct: 72,
        progressiveWfPasses: 16,
        skillfulFootPassScore: 7.5,
        goalsPer90: 0.07,
        xGPer90: 0.05,
        shotAccuracyPct: 42,
        conversionRatePct: 13,
        shotsOnTarget: 10,
        touchesInBox: 52,
        weakFootShotPct: 14,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 33,
        skillfulFootShotScore: 6.6,
        tacklesWonPct: 54,
        interceptions: 38,
        recoveries: 72,
        blocks: 20,
        aerialDuelsWonPct: 44,
        clearances: 48,
        physicalDuelsWonPct: 53,
        strengthDuels: 76,
        balance: 8.1,
        stamina: 8.6,
        bodyContactSuccessPct: 51,
      },
    },
    {
      clubKey: 'river' as const,
      id: 'river-gpirez-003',
      name: 'Leandro González Pirez',
      birthDate: new Date('1992-02-26'),
      nationality: 'Argentina',
      position: Position.CB,
      photoUrl:
        'https://assets.sorare.com/playerpicture/cf06f963-d400-4559-857c-b3fa1350edd4/picture/squared-350eae8e846da14a05b5ad8de6e70f23.png',
      height: 1.86,
      weight: 84,
      preferredFoot: PreferredFoot.LEFT,
      shirtNumber: 14,
      contractStart: new Date('2022-01-01'),
      contractEnd: new Date('2026-12-31'),
      stats: {
        matchesPlayed: 31,
        minutesPlayed: 2620,
        goals: 1,
        assists: 1,
        yellowCards: 9,
        redCards: 0,
        dribblesAttempted: 22,
        dribbleSuccessPct: 48,
        progressiveCarries: 20,
        carriesIntoFinalThird: 8,
        ballRetentionPct: 84,
        foulsWon: 18,
        topSpeed: 28.8,
        sprintDistance: 1080,
        accelerations: 92,
        progressiveRuns: 14,
        distanceCovered: 8.05,
        passAccuracyPct: 89,
        progressivePasses: 48,
        keyPasses: 10,
        throughBalls: 2,
        crossAccuracyPct: 14,
        xA: 0.42,
        weakFootPassPct: 28,
        weakFootPassAccuracyPct: 76,
        progressiveWfPasses: 12,
        skillfulFootPassScore: 7.3,
        goalsPer90: 0.034,
        xGPer90: 0.04,
        shotAccuracyPct: 38,
        conversionRatePct: 10,
        shotsOnTarget: 6,
        touchesInBox: 42,
        weakFootShotPct: 18,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 32,
        skillfulFootShotScore: 6.3,
        tacklesWonPct: 61,
        interceptions: 44,
        recoveries: 82,
        blocks: 34,
        aerialDuelsWonPct: 76,
        clearances: 96,
        physicalDuelsWonPct: 66,
        strengthDuels: 108,
        balance: 7,
        stamina: 7.4,
        bodyContactSuccessPct: 62,
      },
    },
    {
      clubKey: 'river' as const,
      id: 'river-pdiaz-004',
      name: 'Paulo Díaz',
      birthDate: new Date('1994-08-25'),
      nationality: 'Chile',
      position: Position.CB,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/47/00/344700_paulo_diaz_20260222235912.png',
      height: 1.87,
      weight: 82,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 17,
      contractStart: new Date('2020-07-01'),
      contractEnd: new Date('2027-12-31'),
      stats: {
        matchesPlayed: 33,
        minutesPlayed: 2850,
        goals: 2,
        assists: 2,
        yellowCards: 10,
        redCards: 1,
        dribblesAttempted: 28,
        dribbleSuccessPct: 54,
        progressiveCarries: 26,
        carriesIntoFinalThird: 12,
        ballRetentionPct: 85,
        foulsWon: 22,
        topSpeed: 29.5,
        sprintDistance: 1240,
        accelerations: 102,
        progressiveRuns: 20,
        distanceCovered: 8.35,
        passAccuracyPct: 88.5,
        progressivePasses: 55,
        keyPasses: 14,
        throughBalls: 4,
        crossAccuracyPct: 18,
        xA: 0.65,
        weakFootPassPct: 22,
        weakFootPassAccuracyPct: 78,
        progressiveWfPasses: 14,
        skillfulFootPassScore: 7.4,
        goalsPer90: 0.063,
        xGPer90: 0.06,
        shotAccuracyPct: 45,
        conversionRatePct: 15,
        shotsOnTarget: 9,
        touchesInBox: 55,
        weakFootShotPct: 12,
        weakFootGoals: 1,
        weakFootShotAccuracyPct: 40,
        skillfulFootShotScore: 6.8,
        tacklesWonPct: 58,
        interceptions: 46,
        recoveries: 88,
        blocks: 30,
        aerialDuelsWonPct: 72,
        clearances: 88,
        physicalDuelsWonPct: 63,
        strengthDuels: 102,
        balance: 7.2,
        stamina: 7.6,
        bodyContactSuccessPct: 60,
      },
    },
    {
      clubKey: 'river' as const,
      id: 'river-ediaz-005',
      name: 'Enzo Díaz',
      birthDate: new Date('1995-12-07'),
      nationality: 'Argentina',
      position: Position.LB,
      photoUrl:
        'https://cdn-img.staticzz.com/img/planteis/new/51/49/9665149_enzo_diaz_20250108040430.png',
      height: 1.78,
      weight: 72,
      preferredFoot: PreferredFoot.LEFT,
      shirtNumber: 13,
      contractStart: new Date('2021-06-01'),
      contractEnd: new Date('2026-12-31'),
      stats: {
        matchesPlayed: 30,
        minutesPlayed: 2520,
        goals: 0,
        assists: 5,
        yellowCards: 6,
        redCards: 0,
        dribblesAttempted: 48,
        dribbleSuccessPct: 52,
        progressiveCarries: 52,
        carriesIntoFinalThird: 44,
        ballRetentionPct: 80,
        foulsWon: 28,
        topSpeed: 31.8,
        sprintDistance: 1920,
        accelerations: 218,
        progressiveRuns: 54,
        distanceCovered: 9.45,
        passAccuracyPct: 83.5,
        progressivePasses: 46,
        keyPasses: 30,
        throughBalls: 5,
        crossAccuracyPct: 36,
        xA: 4.8,
        weakFootPassPct: 20,
        weakFootPassAccuracyPct: 71,
        progressiveWfPasses: 15,
        skillfulFootPassScore: 7.7,
        goalsPer90: 0,
        xGPer90: 0.03,
        shotAccuracyPct: 28,
        conversionRatePct: 0,
        shotsOnTarget: 4,
        touchesInBox: 38,
        weakFootShotPct: 12,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 25,
        skillfulFootShotScore: 6.2,
        tacklesWonPct: 56,
        interceptions: 36,
        recoveries: 70,
        blocks: 22,
        aerialDuelsWonPct: 50,
        clearances: 52,
        physicalDuelsWonPct: 54,
        strengthDuels: 84,
        balance: 7.5,
        stamina: 8.2,
        bodyContactSuccessPct: 53,
      },
    },
    {
      clubKey: 'river' as const,
      id: 'river-aliendro-006',
      name: 'Rodrigo Aliendro',
      birthDate: new Date('1991-02-11'),
      nationality: 'Argentina',
      position: Position.CM,
      photoUrl:
        'https://cdn-img.staticzz.com/img/planteis/new/42/99/9664299_rodrigo_aliendro_20250720190543.png',
      height: 1.75,
      weight: 71,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 29,
      contractStart: new Date('2022-01-01'),
      contractEnd: new Date('2025-12-31'),
      stats: {
        matchesPlayed: 34,
        minutesPlayed: 2780,
        goals: 5,
        assists: 6,
        yellowCards: 8,
        redCards: 0,
        dribblesAttempted: 58,
        dribbleSuccessPct: 56,
        progressiveCarries: 48,
        carriesIntoFinalThird: 36,
        ballRetentionPct: 82,
        foulsWon: 42,
        topSpeed: 30.6,
        sprintDistance: 1620,
        accelerations: 228,
        progressiveRuns: 52,
        distanceCovered: 10.5,
        passAccuracyPct: 85,
        progressivePasses: 58,
        keyPasses: 44,
        throughBalls: 8,
        crossAccuracyPct: 28,
        xA: 5.5,
        weakFootPassPct: 24,
        weakFootPassAccuracyPct: 77,
        progressiveWfPasses: 22,
        skillfulFootPassScore: 7.9,
        goalsPer90: 0.16,
        xGPer90: 0.12,
        shotAccuracyPct: 46,
        conversionRatePct: 16,
        shotsOnTarget: 22,
        touchesInBox: 68,
        weakFootShotPct: 18,
        weakFootGoals: 1,
        weakFootShotAccuracyPct: 40,
        skillfulFootShotScore: 7.1,
        tacklesWonPct: 52,
        interceptions: 42,
        recoveries: 96,
        blocks: 16,
        aerialDuelsWonPct: 48,
        clearances: 30,
        physicalDuelsWonPct: 56,
        strengthDuels: 92,
        balance: 7.7,
        stamina: 8.7,
        bodyContactSuccessPct: 54,
      },
    },
    {
      clubKey: 'river' as const,
      id: 'river-eperez-007',
      name: 'Enzo Pérez',
      birthDate: new Date('1986-02-22'),
      nationality: 'Argentina',
      position: Position.CDM,
      photoUrl:
        'https://cdn-img.staticzz.com/img/planteis/new/13/04/7511304_enzo_perez_20250105004209.png',
      height: 1.78,
      weight: 76,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 24,
      contractStart: new Date('2021-07-01'),
      contractEnd: new Date('2024-12-31'),
      stats: {
        matchesPlayed: 28,
        minutesPlayed: 2240,
        goals: 0,
        assists: 3,
        yellowCards: 11,
        redCards: 0,
        dribblesAttempted: 32,
        dribbleSuccessPct: 58,
        progressiveCarries: 28,
        carriesIntoFinalThird: 18,
        ballRetentionPct: 86,
        foulsWon: 22,
        topSpeed: 27.5,
        sprintDistance: 920,
        accelerations: 118,
        progressiveRuns: 28,
        distanceCovered: 9.85,
        passAccuracyPct: 88,
        progressivePasses: 52,
        keyPasses: 36,
        throughBalls: 11,
        crossAccuracyPct: 22,
        xA: 3.8,
        weakFootPassPct: 20,
        weakFootPassAccuracyPct: 82,
        progressiveWfPasses: 18,
        skillfulFootPassScore: 8.2,
        goalsPer90: 0,
        xGPer90: 0.02,
        shotAccuracyPct: 30,
        conversionRatePct: 0,
        shotsOnTarget: 5,
        touchesInBox: 28,
        weakFootShotPct: 10,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 28,
        skillfulFootShotScore: 6,
        tacklesWonPct: 62,
        interceptions: 52,
        recoveries: 108,
        blocks: 24,
        aerialDuelsWonPct: 46,
        clearances: 34,
        physicalDuelsWonPct: 57,
        strengthDuels: 88,
        balance: 7.4,
        stamina: 7.8,
        bodyContactSuccessPct: 58,
      },
    },
    {
      clubKey: 'river' as const,
      id: 'river-barco-008',
      name: 'Esequiel Barco',
      birthDate: new Date('1996-02-29'),
      nationality: 'Argentina',
      position: Position.LW,
      photoUrl:
        'https://cdn-img.staticzz.com/img/planteis/new/13/14/7511314_esequiel_barco_20260115042327.png',
      height: 1.6,
      weight: 62,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 10,
      contractStart: new Date('2023-07-01'),
      contractEnd: new Date('2028-12-31'),
      stats: {
        matchesPlayed: 32,
        minutesPlayed: 2420,
        goals: 7,
        assists: 9,
        yellowCards: 4,
        redCards: 0,
        dribblesAttempted: 138,
        dribbleSuccessPct: 64,
        progressiveCarries: 78,
        carriesIntoFinalThird: 64,
        ballRetentionPct: 77,
        foulsWon: 62,
        topSpeed: 32.4,
        sprintDistance: 2160,
        accelerations: 308,
        progressiveRuns: 86,
        distanceCovered: 9.15,
        passAccuracyPct: 81,
        progressivePasses: 52,
        keyPasses: 56,
        throughBalls: 14,
        crossAccuracyPct: 31,
        xA: 8.2,
        weakFootPassPct: 32,
        weakFootPassAccuracyPct: 71,
        progressiveWfPasses: 28,
        skillfulFootPassScore: 8.5,
        goalsPer90: 0.26,
        xGPer90: 0.22,
        shotAccuracyPct: 52,
        conversionRatePct: 18,
        shotsOnTarget: 30,
        touchesInBox: 102,
        weakFootShotPct: 24,
        weakFootGoals: 2,
        weakFootShotAccuracyPct: 46,
        skillfulFootShotScore: 7.6,
        tacklesWonPct: 42,
        interceptions: 22,
        recoveries: 58,
        blocks: 10,
        aerialDuelsWonPct: 36,
        clearances: 14,
        physicalDuelsWonPct: 44,
        strengthDuels: 58,
        balance: 8.6,
        stamina: 8,
        bodyContactSuccessPct: 45,
      },
    },
    {
      clubKey: 'river' as const,
      id: 'river-borja-009',
      name: 'Miguel Borja',
      birthDate: new Date('1993-01-26'),
      nationality: 'Colombia',
      position: Position.ST,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/90/71/269071_miguel_borja_20250618093133.png',
      height: 1.84,
      weight: 83,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 9,
      contractStart: new Date('2022-01-01'),
      contractEnd: new Date('2026-12-31'),
      stats: {
        matchesPlayed: 36,
        minutesPlayed: 2720,
        goals: 18,
        assists: 4,
        yellowCards: 5,
        redCards: 0,
        dribblesAttempted: 72,
        dribbleSuccessPct: 52,
        progressiveCarries: 42,
        carriesIntoFinalThird: 35,
        ballRetentionPct: 70,
        foulsWon: 48,
        topSpeed: 31,
        sprintDistance: 1720,
        accelerations: 215,
        progressiveRuns: 62,
        distanceCovered: 8.65,
        passAccuracyPct: 74,
        progressivePasses: 34,
        keyPasses: 26,
        throughBalls: 5,
        crossAccuracyPct: 20,
        xA: 3.2,
        weakFootPassPct: 20,
        weakFootPassAccuracyPct: 64,
        progressiveWfPasses: 14,
        skillfulFootPassScore: 7.2,
        goalsPer90: 0.6,
        xGPer90: 0.55,
        shotAccuracyPct: 56,
        conversionRatePct: 23,
        shotsOnTarget: 52,
        touchesInBox: 142,
        weakFootShotPct: 18,
        weakFootGoals: 4,
        weakFootShotAccuracyPct: 50,
        skillfulFootShotScore: 8.2,
        tacklesWonPct: 38,
        interceptions: 12,
        recoveries: 42,
        blocks: 8,
        aerialDuelsWonPct: 68,
        clearances: 14,
        physicalDuelsWonPct: 60,
        strengthDuels: 98,
        balance: 7.6,
        stamina: 7.5,
        bodyContactSuccessPct: 59,
      },
    },
    {
      clubKey: 'river' as const,
      id: 'river-solari-010',
      name: 'Pablo Solari',
      birthDate: new Date('2001-03-22'),
      nationality: 'Argentina',
      position: Position.RW,
      photoUrl:
        'https://cdn-img.staticzz.com/img/planteis/new/26/84/7052684_pablo_solari_20250321185901.png',
      height: 1.7,
      weight: 67,
      preferredFoot: PreferredFoot.LEFT,
      shirtNumber: 11,
      contractStart: new Date('2022-07-01'),
      contractEnd: new Date('2027-12-31'),
      stats: {
        matchesPlayed: 33,
        minutesPlayed: 2180,
        goals: 8,
        assists: 7,
        yellowCards: 3,
        redCards: 0,
        dribblesAttempted: 118,
        dribbleSuccessPct: 61,
        progressiveCarries: 76,
        carriesIntoFinalThird: 58,
        ballRetentionPct: 76,
        foulsWon: 48,
        topSpeed: 33.5,
        sprintDistance: 2280,
        accelerations: 292,
        progressiveRuns: 78,
        distanceCovered: 9.05,
        passAccuracyPct: 79.5,
        progressivePasses: 46,
        keyPasses: 42,
        throughBalls: 9,
        crossAccuracyPct: 30,
        xA: 6.8,
        weakFootPassPct: 26,
        weakFootPassAccuracyPct: 69,
        progressiveWfPasses: 21,
        skillfulFootPassScore: 7.9,
        goalsPer90: 0.33,
        xGPer90: 0.3,
        shotAccuracyPct: 50,
        conversionRatePct: 19,
        shotsOnTarget: 32,
        touchesInBox: 92,
        weakFootShotPct: 16,
        weakFootGoals: 2,
        weakFootShotAccuracyPct: 44,
        skillfulFootShotScore: 7.5,
        tacklesWonPct: 44,
        interceptions: 24,
        recoveries: 62,
        blocks: 11,
        aerialDuelsWonPct: 40,
        clearances: 16,
        physicalDuelsWonPct: 46,
        strengthDuels: 68,
        balance: 8.2,
        stamina: 8.1,
        bodyContactSuccessPct: 46,
      },
    },
    {
      clubKey: 'river' as const,
      id: 'river-delacruz-011',
      name: 'Nicolás De La Cruz',
      birthDate: new Date('1997-06-01'),
      nationality: 'Uruguay',
      position: Position.CAM,
      photoUrl:
        'https://assets.sorare.com/playerpicture/7b516674-b2d7-4753-8cea-0a8b9d4f07d0/picture/squared-8b5159518e2803a493830ea478f18986.png',
      height: 1.67,
      weight: 64,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 5,
      contractStart: new Date('2017-07-01'),
      contractEnd: new Date('2023-12-31'),
      stats: {
        matchesPlayed: 30,
        minutesPlayed: 2480,
        goals: 9,
        assists: 8,
        yellowCards: 9,
        redCards: 1,
        dribblesAttempted: 108,
        dribbleSuccessPct: 60,
        progressiveCarries: 70,
        carriesIntoFinalThird: 58,
        ballRetentionPct: 81,
        foulsWon: 54,
        topSpeed: 31.6,
        sprintDistance: 1980,
        accelerations: 268,
        progressiveRuns: 68,
        distanceCovered: 10.15,
        passAccuracyPct: 84.5,
        progressivePasses: 64,
        keyPasses: 58,
        throughBalls: 16,
        crossAccuracyPct: 29,
        xA: 7.2,
        weakFootPassPct: 26,
        weakFootPassAccuracyPct: 76,
        progressiveWfPasses: 27,
        skillfulFootPassScore: 8.4,
        goalsPer90: 0.33,
        xGPer90: 0.28,
        shotAccuracyPct: 52,
        conversionRatePct: 21,
        shotsOnTarget: 34,
        touchesInBox: 118,
        weakFootShotPct: 22,
        weakFootGoals: 3,
        weakFootShotAccuracyPct: 48,
        skillfulFootShotScore: 7.8,
        tacklesWonPct: 46,
        interceptions: 32,
        recoveries: 82,
        blocks: 15,
        aerialDuelsWonPct: 42,
        clearances: 20,
        physicalDuelsWonPct: 51,
        strengthDuels: 78,
        balance: 8.4,
        stamina: 8.3,
        bodyContactSuccessPct: 49,
      },
    },
    {
      clubKey: 'barcelona' as const,
      id: 'barca-kounde-001',
      name: 'Jules Koundé',
      birthDate: new Date('1998-11-12'),
      nationality: 'France',
      position: Position.CB,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/35/38/493538_jules_kounde_20250929145657.png',
      height: 1.78,
      weight: 75,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 23,
      contractStart: new Date('2022-07-28'),
      contractEnd: new Date('2027-06-30'),
      stats: {
        matchesPlayed: 36,
        minutesPlayed: 3080,
        goals: 2,
        assists: 4,
        yellowCards: 6,
        redCards: 0,
        dribblesAttempted: 32,
        dribbleSuccessPct: 56,
        progressiveCarries: 28,
        carriesIntoFinalThird: 14,
        ballRetentionPct: 86,
        foulsWon: 20,
        topSpeed: 30.2,
        sprintDistance: 1280,
        accelerations: 112,
        progressiveRuns: 22,
        distanceCovered: 8.6,
        passAccuracyPct: 90,
        progressivePasses: 56,
        keyPasses: 16,
        throughBalls: 4,
        crossAccuracyPct: 20,
        xA: 0.85,
        weakFootPassPct: 18,
        weakFootPassAccuracyPct: 80,
        progressiveWfPasses: 14,
        skillfulFootPassScore: 7.6,
        goalsPer90: 0.058,
        xGPer90: 0.05,
        shotAccuracyPct: 44,
        conversionRatePct: 12,
        shotsOnTarget: 11,
        touchesInBox: 48,
        weakFootShotPct: 12,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 30,
        skillfulFootShotScore: 6.4,
        tacklesWonPct: 64,
        interceptions: 48,
        recoveries: 86,
        blocks: 28,
        aerialDuelsWonPct: 62,
        clearances: 72,
        physicalDuelsWonPct: 60,
        strengthDuels: 94,
        balance: 7.8,
        stamina: 8,
        bodyContactSuccessPct: 58,
      },
    },
    {
      clubKey: 'barcelona' as const,
      id: 'barca-araujo-002',
      name: 'Ronald Araújo',
      birthDate: new Date('1999-03-07'),
      nationality: 'Uruguay',
      position: Position.CB,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/17/42/591742_ronald_araujo_20251019000808.png',
      height: 1.91,
      weight: 92,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 4,
      contractStart: new Date('2020-10-05'),
      contractEnd: new Date('2026-06-30'),
      stats: {
        matchesPlayed: 28,
        minutesPlayed: 2350,
        goals: 1,
        assists: 0,
        yellowCards: 7,
        redCards: 0,
        dribblesAttempted: 18,
        dribbleSuccessPct: 50,
        progressiveCarries: 16,
        carriesIntoFinalThird: 7,
        ballRetentionPct: 84,
        foulsWon: 16,
        topSpeed: 31.5,
        sprintDistance: 1420,
        accelerations: 118,
        progressiveRuns: 18,
        distanceCovered: 8.15,
        passAccuracyPct: 88,
        progressivePasses: 42,
        keyPasses: 8,
        throughBalls: 2,
        crossAccuracyPct: 12,
        xA: 0.25,
        weakFootPassPct: 22,
        weakFootPassAccuracyPct: 72,
        progressiveWfPasses: 10,
        skillfulFootPassScore: 7.1,
        goalsPer90: 0.038,
        xGPer90: 0.04,
        shotAccuracyPct: 36,
        conversionRatePct: 9,
        shotsOnTarget: 6,
        touchesInBox: 52,
        weakFootShotPct: 15,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 28,
        skillfulFootShotScore: 6.2,
        tacklesWonPct: 66,
        interceptions: 38,
        recoveries: 78,
        blocks: 40,
        aerialDuelsWonPct: 78,
        clearances: 98,
        physicalDuelsWonPct: 70,
        strengthDuels: 118,
        balance: 7.5,
        stamina: 7.8,
        bodyContactSuccessPct: 65,
      },
    },
    {
      clubKey: 'barcelona' as const,
      id: 'barca-balde-003',
      name: 'Alejandro Balde',
      birthDate: new Date('2003-10-18'),
      nationality: 'Spain',
      position: Position.LB,
      photoUrl:
        'https://static.sky.it/editorialstaticimages/c1ea1340ece54c5e94c68c29fc8b4157/sport/headshots/calcio/club/493019.png?im=Resize,width=270',
      height: 1.75,
      weight: 72,
      preferredFoot: PreferredFoot.LEFT,
      shirtNumber: 3,
      contractStart: new Date('2020-07-01'),
      contractEnd: new Date('2027-06-30'),
      stats: {
        matchesPlayed: 33,
        minutesPlayed: 2860,
        goals: 1,
        assists: 5,
        yellowCards: 5,
        redCards: 0,
        dribblesAttempted: 88,
        dribbleSuccessPct: 59,
        progressiveCarries: 74,
        carriesIntoFinalThird: 62,
        ballRetentionPct: 80,
        foulsWon: 38,
        topSpeed: 33.8,
        sprintDistance: 2260,
        accelerations: 288,
        progressiveRuns: 78,
        distanceCovered: 9.75,
        passAccuracyPct: 85,
        progressivePasses: 52,
        keyPasses: 34,
        throughBalls: 6,
        crossAccuracyPct: 34,
        xA: 4.5,
        weakFootPassPct: 20,
        weakFootPassAccuracyPct: 70,
        progressiveWfPasses: 18,
        skillfulFootPassScore: 7.8,
        goalsPer90: 0.031,
        xGPer90: 0.04,
        shotAccuracyPct: 35,
        conversionRatePct: 8,
        shotsOnTarget: 7,
        touchesInBox: 56,
        weakFootShotPct: 10,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 25,
        skillfulFootShotScore: 6.3,
        tacklesWonPct: 58,
        interceptions: 42,
        recoveries: 76,
        blocks: 22,
        aerialDuelsWonPct: 46,
        clearances: 46,
        physicalDuelsWonPct: 54,
        strengthDuels: 82,
        balance: 8.2,
        stamina: 8.8,
        bodyContactSuccessPct: 52,
      },
    },
    {
      clubKey: 'barcelona' as const,
      id: 'barca-cancelo-004',
      name: 'João Cancelo',
      birthDate: new Date('1994-05-27'),
      nationality: 'Portugal',
      position: Position.RB,
      photoUrl:
        'https://www.zerozero.com.ar/img/jogadores/new/49/41/74941_joao_cancelo_20251228003912.png',
      height: 1.82,
      weight: 77,
      preferredFoot: PreferredFoot.LEFT,
      shirtNumber: 2,
      contractStart: new Date('2023-09-01'),
      contractEnd: new Date('2024-06-30'),
      stats: {
        matchesPlayed: 34,
        minutesPlayed: 2920,
        goals: 4,
        assists: 7,
        yellowCards: 8,
        redCards: 0,
        dribblesAttempted: 76,
        dribbleSuccessPct: 57,
        progressiveCarries: 82,
        carriesIntoFinalThird: 68,
        ballRetentionPct: 81,
        foulsWon: 32,
        topSpeed: 32.1,
        sprintDistance: 1980,
        accelerations: 242,
        progressiveRuns: 72,
        distanceCovered: 9.95,
        passAccuracyPct: 86,
        progressivePasses: 64,
        keyPasses: 48,
        throughBalls: 10,
        crossAccuracyPct: 36,
        xA: 6.2,
        weakFootPassPct: 32,
        weakFootPassAccuracyPct: 78,
        progressiveWfPasses: 24,
        skillfulFootPassScore: 8.2,
        goalsPer90: 0.12,
        xGPer90: 0.11,
        shotAccuracyPct: 48,
        conversionRatePct: 16,
        shotsOnTarget: 18,
        touchesInBox: 78,
        weakFootShotPct: 18,
        weakFootGoals: 1,
        weakFootShotAccuracyPct: 42,
        skillfulFootShotScore: 7.4,
        tacklesWonPct: 56,
        interceptions: 46,
        recoveries: 80,
        blocks: 24,
        aerialDuelsWonPct: 52,
        clearances: 52,
        physicalDuelsWonPct: 56,
        strengthDuels: 88,
        balance: 7.9,
        stamina: 8.6,
        bodyContactSuccessPct: 54,
      },
    },
    {
      clubKey: 'barcelona' as const,
      id: 'barca-ferrantorres-005',
      name: 'Ferran Torres',
      birthDate: new Date('2000-02-29'),
      nationality: 'Spain',
      position: Position.LW,
      photoUrl:
        'https://cdn-img.staticzz.com/img/planteis/new/77/39/11527739_ferran_torres_20240914122906.png',
      height: 1.85,
      weight: 77,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 7,
      contractStart: new Date('2021-12-28'),
      contractEnd: new Date('2027-06-30'),
      stats: {
        matchesPlayed: 32,
        minutesPlayed: 2280,
        goals: 11,
        assists: 4,
        yellowCards: 3,
        redCards: 0,
        dribblesAttempted: 86,
        dribbleSuccessPct: 54,
        progressiveCarries: 58,
        carriesIntoFinalThird: 52,
        ballRetentionPct: 78,
        foulsWon: 28,
        topSpeed: 32.4,
        sprintDistance: 2020,
        accelerations: 248,
        progressiveRuns: 68,
        distanceCovered: 9.05,
        passAccuracyPct: 82,
        progressivePasses: 46,
        keyPasses: 38,
        throughBalls: 8,
        crossAccuracyPct: 28,
        xA: 4.6,
        weakFootPassPct: 18,
        weakFootPassAccuracyPct: 70,
        progressiveWfPasses: 16,
        skillfulFootPassScore: 7.8,
        goalsPer90: 0.43,
        xGPer90: 0.38,
        shotAccuracyPct: 51,
        conversionRatePct: 20,
        shotsOnTarget: 44,
        touchesInBox: 136,
        weakFootShotPct: 14,
        weakFootGoals: 2,
        weakFootShotAccuracyPct: 44,
        skillfulFootShotScore: 7.9,
        tacklesWonPct: 42,
        interceptions: 22,
        recoveries: 54,
        blocks: 10,
        aerialDuelsWonPct: 44,
        clearances: 12,
        physicalDuelsWonPct: 50,
        strengthDuels: 76,
        balance: 7.9,
        stamina: 8.2,
        bodyContactSuccessPct: 48,
      },
    },
    {
      clubKey: 'barcelona' as const,
      id: 'barca-dejong-006',
      name: 'Frenkie de Jong',
      birthDate: new Date('1997-05-12'),
      nationality: 'Netherlands',
      position: Position.CM,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/04/65/460465_frenkie_de_jong_20250817021001.png',
      height: 1.81,
      weight: 74,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 21,
      contractStart: new Date('2019-07-01'),
      contractEnd: new Date('2026-06-30'),
      stats: {
        matchesPlayed: 32,
        minutesPlayed: 2680,
        goals: 2,
        assists: 6,
        yellowCards: 5,
        redCards: 0,
        dribblesAttempted: 86,
        dribbleSuccessPct: 62,
        progressiveCarries: 88,
        carriesIntoFinalThird: 64,
        ballRetentionPct: 90,
        foulsWon: 36,
        topSpeed: 29.8,
        sprintDistance: 1380,
        accelerations: 168,
        progressiveRuns: 58,
        distanceCovered: 10.35,
        passAccuracyPct: 91.5,
        progressivePasses: 82,
        keyPasses: 48,
        throughBalls: 12,
        crossAccuracyPct: 22,
        xA: 5.4,
        weakFootPassPct: 28,
        weakFootPassAccuracyPct: 82,
        progressiveWfPasses: 28,
        skillfulFootPassScore: 8.6,
        goalsPer90: 0.067,
        xGPer90: 0.06,
        shotAccuracyPct: 46,
        conversionRatePct: 11,
        shotsOnTarget: 14,
        touchesInBox: 72,
        weakFootShotPct: 16,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 38,
        skillfulFootShotScore: 6.9,
        tacklesWonPct: 58,
        interceptions: 46,
        recoveries: 94,
        blocks: 20,
        aerialDuelsWonPct: 54,
        clearances: 32,
        physicalDuelsWonPct: 56,
        strengthDuels: 88,
        balance: 8.5,
        stamina: 8.6,
        bodyContactSuccessPct: 55,
      },
    },
    {
      clubKey: 'barcelona' as const,
      id: 'barca-pedri-007',
      name: 'Pedri',
      birthDate: new Date('2002-11-25'),
      nationality: 'Spain',
      position: Position.CM,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/96/13/739613_pedri_gonzalez_20251019000639.png',
      height: 1.74,
      weight: 60,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 8,
      contractStart: new Date('2019-09-01'),
      contractEnd: new Date('2026-06-30'),
      stats: {
        matchesPlayed: 26,
        minutesPlayed: 1980,
        goals: 4,
        assists: 5,
        yellowCards: 2,
        redCards: 0,
        dribblesAttempted: 64,
        dribbleSuccessPct: 64,
        progressiveCarries: 52,
        carriesIntoFinalThird: 44,
        ballRetentionPct: 91,
        foulsWon: 32,
        topSpeed: 28.4,
        sprintDistance: 1020,
        accelerations: 142,
        progressiveRuns: 42,
        distanceCovered: 9.45,
        passAccuracyPct: 92,
        progressivePasses: 68,
        keyPasses: 44,
        throughBalls: 18,
        crossAccuracyPct: 24,
        xA: 5.8,
        weakFootPassPct: 22,
        weakFootPassAccuracyPct: 85,
        progressiveWfPasses: 22,
        skillfulFootPassScore: 8.8,
        goalsPer90: 0.18,
        xGPer90: 0.14,
        shotAccuracyPct: 50,
        conversionRatePct: 15,
        shotsOnTarget: 18,
        touchesInBox: 88,
        weakFootShotPct: 18,
        weakFootGoals: 1,
        weakFootShotAccuracyPct: 44,
        skillfulFootShotScore: 7.2,
        tacklesWonPct: 54,
        interceptions: 38,
        recoveries: 78,
        blocks: 16,
        aerialDuelsWonPct: 38,
        clearances: 18,
        physicalDuelsWonPct: 48,
        strengthDuels: 62,
        balance: 8.7,
        stamina: 8.2,
        bodyContactSuccessPct: 45,
      },
    },
    {
      clubKey: 'barcelona' as const,
      id: 'barca-gavi-008',
      name: 'Gavi',
      birthDate: new Date('2004-08-05'),
      nationality: 'Spain',
      position: Position.CM,
      photoUrl:
        'https://cdn-img.staticzz.com/img/planteis/new/47/36/11534736_pablo_gavi_20240914123210.png',
      height: 1.73,
      weight: 68,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 6,
      contractStart: new Date('2021-07-01'),
      contractEnd: new Date('2026-06-30'),
      stats: {
        matchesPlayed: 28,
        minutesPlayed: 2320,
        goals: 2,
        assists: 4,
        yellowCards: 14,
        redCards: 1,
        dribblesAttempted: 72,
        dribbleSuccessPct: 55,
        progressiveCarries: 48,
        carriesIntoFinalThird: 40,
        ballRetentionPct: 84,
        foulsWon: 42,
        topSpeed: 30.1,
        sprintDistance: 1520,
        accelerations: 238,
        progressiveRuns: 52,
        distanceCovered: 10.85,
        passAccuracyPct: 87,
        progressivePasses: 54,
        keyPasses: 34,
        throughBalls: 8,
        crossAccuracyPct: 26,
        xA: 4.2,
        weakFootPassPct: 24,
        weakFootPassAccuracyPct: 78,
        progressiveWfPasses: 18,
        skillfulFootPassScore: 7.9,
        goalsPer90: 0.078,
        xGPer90: 0.07,
        shotAccuracyPct: 44,
        conversionRatePct: 12,
        shotsOnTarget: 12,
        touchesInBox: 64,
        weakFootShotPct: 20,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 35,
        skillfulFootShotScore: 6.8,
        tacklesWonPct: 60,
        interceptions: 48,
        recoveries: 96,
        blocks: 22,
        aerialDuelsWonPct: 44,
        clearances: 24,
        physicalDuelsWonPct: 58,
        strengthDuels: 96,
        balance: 8,
        stamina: 9,
        bodyContactSuccessPct: 56,
      },
    },
    {
      clubKey: 'barcelona' as const,
      id: 'barca-lewandowski-009',
      name: 'Robert Lewandowski',
      birthDate: new Date('1988-08-21'),
      nationality: 'Poland',
      position: Position.ST,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/10/23/71023_robert_lewandowski_20250929145802.png',
      height: 1.85,
      weight: 81,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 9,
      contractStart: new Date('2022-07-17'),
      contractEnd: new Date('2026-06-30'),
      stats: {
        matchesPlayed: 35,
        minutesPlayed: 2980,
        goals: 19,
        assists: 6,
        yellowCards: 3,
        redCards: 0,
        dribblesAttempted: 72,
        dribbleSuccessPct: 54,
        progressiveCarries: 46,
        carriesIntoFinalThird: 35,
        ballRetentionPct: 78,
        foulsWon: 28,
        topSpeed: 30.5,
        sprintDistance: 1580,
        accelerations: 188,
        progressiveRuns: 54,
        distanceCovered: 8.45,
        passAccuracyPct: 78,
        progressivePasses: 38,
        keyPasses: 32,
        throughBalls: 7,
        crossAccuracyPct: 18,
        xA: 3.8,
        weakFootPassPct: 18,
        weakFootPassAccuracyPct: 70,
        progressiveWfPasses: 14,
        skillfulFootPassScore: 7.6,
        goalsPer90: 0.57,
        xGPer90: 0.52,
        shotAccuracyPct: 58,
        conversionRatePct: 24,
        shotsOnTarget: 62,
        touchesInBox: 158,
        weakFootShotPct: 14,
        weakFootGoals: 4,
        weakFootShotAccuracyPct: 50,
        skillfulFootShotScore: 8.9,
        tacklesWonPct: 36,
        interceptions: 10,
        recoveries: 38,
        blocks: 8,
        aerialDuelsWonPct: 64,
        clearances: 12,
        physicalDuelsWonPct: 58,
        strengthDuels: 96,
        balance: 8.1,
        stamina: 7.8,
        bodyContactSuccessPct: 60,
      },
    },
    {
      clubKey: 'barcelona' as const,
      id: 'barca-raphinha-010',
      name: 'Raphinha',
      birthDate: new Date('1996-12-14'),
      nationality: 'Brazil',
      position: Position.RW,
      photoUrl:
        'https://cdn-img.staticzz.com/img/planteis/new/77/30/7057730_raphinha_20241204153208.png',
      height: 1.76,
      weight: 68,
      preferredFoot: PreferredFoot.LEFT,
      shirtNumber: 11,
      contractStart: new Date('2022-07-13'),
      contractEnd: new Date('2027-06-30'),
      stats: {
        matchesPlayed: 34,
        minutesPlayed: 2650,
        goals: 8,
        assists: 11,
        yellowCards: 6,
        redCards: 0,
        dribblesAttempted: 128,
        dribbleSuccessPct: 58,
        progressiveCarries: 82,
        carriesIntoFinalThird: 66,
        ballRetentionPct: 77,
        foulsWon: 58,
        topSpeed: 32.8,
        sprintDistance: 2140,
        accelerations: 296,
        progressiveRuns: 84,
        distanceCovered: 9.25,
        passAccuracyPct: 82,
        progressivePasses: 54,
        keyPasses: 56,
        throughBalls: 12,
        crossAccuracyPct: 32,
        xA: 9.2,
        weakFootPassPct: 28,
        weakFootPassAccuracyPct: 72,
        progressiveWfPasses: 24,
        skillfulFootPassScore: 8.3,
        goalsPer90: 0.27,
        xGPer90: 0.26,
        shotAccuracyPct: 48,
        conversionRatePct: 17,
        shotsOnTarget: 38,
        touchesInBox: 112,
        weakFootShotPct: 20,
        weakFootGoals: 2,
        weakFootShotAccuracyPct: 46,
        skillfulFootShotScore: 7.6,
        tacklesWonPct: 46,
        interceptions: 28,
        recoveries: 64,
        blocks: 12,
        aerialDuelsWonPct: 36,
        clearances: 14,
        physicalDuelsWonPct: 48,
        strengthDuels: 70,
        balance: 8.3,
        stamina: 8.5,
        bodyContactSuccessPct: 47,
      },
    },
    {
      clubKey: 'realMadrid' as const,
      id: 'madrid-carvajal-001',
      name: 'Dani Carvajal',
      birthDate: new Date('1992-01-11'),
      nationality: 'Spain',
      position: Position.RB,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/48/33/134833_dani_carvajal_20240809095322.png',
      height: 1.73,
      weight: 73,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 2,
      contractStart: new Date('2013-07-01'),
      contractEnd: new Date('2025-06-30'),
      stats: {
        matchesPlayed: 32,
        minutesPlayed: 2720,
        goals: 2,
        assists: 5,
        yellowCards: 9,
        redCards: 0,
        dribblesAttempted: 48,
        dribbleSuccessPct: 52,
        progressiveCarries: 52,
        carriesIntoFinalThird: 42,
        ballRetentionPct: 82,
        foulsWon: 26,
        topSpeed: 31.4,
        sprintDistance: 1760,
        accelerations: 208,
        progressiveRuns: 50,
        distanceCovered: 9.55,
        passAccuracyPct: 87,
        progressivePasses: 44,
        keyPasses: 36,
        throughBalls: 5,
        crossAccuracyPct: 30,
        xA: 4.8,
        weakFootPassPct: 18,
        weakFootPassAccuracyPct: 74,
        progressiveWfPasses: 14,
        skillfulFootPassScore: 7.6,
        goalsPer90: 0.066,
        xGPer90: 0.06,
        shotAccuracyPct: 40,
        conversionRatePct: 12,
        shotsOnTarget: 10,
        touchesInBox: 48,
        weakFootShotPct: 12,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 30,
        skillfulFootShotScore: 6.5,
        tacklesWonPct: 60,
        interceptions: 44,
        recoveries: 78,
        blocks: 28,
        aerialDuelsWonPct: 48,
        clearances: 56,
        physicalDuelsWonPct: 58,
        strengthDuels: 90,
        balance: 7.8,
        stamina: 8.5,
        bodyContactSuccessPct: 57,
      },
    },
    {
      clubKey: 'realMadrid' as const,
      id: 'madrid-rudiger-002',
      name: 'Antonio Rüdiger',
      birthDate: new Date('1993-03-03'),
      nationality: 'Germany',
      position: Position.CB,
      photoUrl:
        'https://cdn-img.zerozero.pt/img/jogadores/new/68/01/206801_antonio_rudiger_20260217194428.png',
      height: 1.9,
      weight: 86,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 22,
      contractStart: new Date('2022-07-01'),
      contractEnd: new Date('2026-06-30'),
      stats: {
        matchesPlayed: 35,
        minutesPlayed: 3020,
        goals: 1,
        assists: 2,
        yellowCards: 11,
        redCards: 0,
        dribblesAttempted: 26,
        dribbleSuccessPct: 48,
        progressiveCarries: 22,
        carriesIntoFinalThird: 10,
        ballRetentionPct: 84,
        foulsWon: 18,
        topSpeed: 30.8,
        sprintDistance: 1320,
        accelerations: 108,
        progressiveRuns: 16,
        distanceCovered: 8.45,
        passAccuracyPct: 89,
        progressivePasses: 48,
        keyPasses: 12,
        throughBalls: 3,
        crossAccuracyPct: 14,
        xA: 0.52,
        weakFootPassPct: 20,
        weakFootPassAccuracyPct: 76,
        progressiveWfPasses: 12,
        skillfulFootPassScore: 7.2,
        goalsPer90: 0.03,
        xGPer90: 0.04,
        shotAccuracyPct: 38,
        conversionRatePct: 10,
        shotsOnTarget: 8,
        touchesInBox: 58,
        weakFootShotPct: 14,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 32,
        skillfulFootShotScore: 6.4,
        tacklesWonPct: 63,
        interceptions: 42,
        recoveries: 84,
        blocks: 36,
        aerialDuelsWonPct: 74,
        clearances: 94,
        physicalDuelsWonPct: 68,
        strengthDuels: 114,
        balance: 7.4,
        stamina: 7.9,
        bodyContactSuccessPct: 64,
      },
    },
    {
      clubKey: 'realMadrid' as const,
      id: 'madrid-alaba-003',
      name: 'David Alaba',
      birthDate: new Date('1992-06-24'),
      nationality: 'Austria',
      position: Position.CB,
      photoUrl:
        'https://www.zerozero.com.ar/img/jogadores/new/84/00/108400_david_alaba_20250406000004.png',
      height: 1.8,
      weight: 78,
      preferredFoot: PreferredFoot.LEFT,
      shirtNumber: 4,
      contractStart: new Date('2021-07-01'),
      contractEnd: new Date('2026-06-30'),
      stats: {
        matchesPlayed: 30,
        minutesPlayed: 2450,
        goals: 0,
        assists: 3,
        yellowCards: 4,
        redCards: 0,
        dribblesAttempted: 28,
        dribbleSuccessPct: 58,
        progressiveCarries: 32,
        carriesIntoFinalThird: 18,
        ballRetentionPct: 89,
        foulsWon: 14,
        topSpeed: 29.5,
        sprintDistance: 1180,
        accelerations: 98,
        progressiveRuns: 24,
        distanceCovered: 8.2,
        passAccuracyPct: 91,
        progressivePasses: 62,
        keyPasses: 20,
        throughBalls: 6,
        crossAccuracyPct: 22,
        xA: 0.95,
        weakFootPassPct: 35,
        weakFootPassAccuracyPct: 82,
        progressiveWfPasses: 18,
        skillfulFootPassScore: 8.1,
        goalsPer90: 0,
        xGPer90: 0.04,
        shotAccuracyPct: 28,
        conversionRatePct: 0,
        shotsOnTarget: 5,
        touchesInBox: 42,
        weakFootShotPct: 20,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 30,
        skillfulFootShotScore: 6.2,
        tacklesWonPct: 58,
        interceptions: 40,
        recoveries: 76,
        blocks: 28,
        aerialDuelsWonPct: 58,
        clearances: 68,
        physicalDuelsWonPct: 56,
        strengthDuels: 84,
        balance: 8,
        stamina: 7.7,
        bodyContactSuccessPct: 54,
      },
    },
    {
      clubKey: 'realMadrid' as const,
      id: 'madrid-mendy-004',
      name: 'Ferland Mendy',
      birthDate: new Date('1995-06-08'),
      nationality: 'France',
      position: Position.LB,
      photoUrl:
        'https://www.zerozero.com.ar/img/jogadores/new/40/10/454010_ferland_mendy_20240809100319.png',
      height: 1.8,
      weight: 73,
      preferredFoot: PreferredFoot.LEFT,
      shirtNumber: 23,
      contractStart: new Date('2019-07-01'),
      contractEnd: new Date('2025-06-30'),
      stats: {
        matchesPlayed: 31,
        minutesPlayed: 2580,
        goals: 0,
        assists: 4,
        yellowCards: 5,
        redCards: 0,
        dribblesAttempted: 58,
        dribbleSuccessPct: 56,
        progressiveCarries: 62,
        carriesIntoFinalThird: 48,
        ballRetentionPct: 85,
        foulsWon: 22,
        topSpeed: 32.6,
        sprintDistance: 2040,
        accelerations: 248,
        progressiveRuns: 58,
        distanceCovered: 9.35,
        passAccuracyPct: 87,
        progressivePasses: 48,
        keyPasses: 28,
        throughBalls: 4,
        crossAccuracyPct: 28,
        xA: 3.6,
        weakFootPassPct: 16,
        weakFootPassAccuracyPct: 72,
        progressiveWfPasses: 12,
        skillfulFootPassScore: 7.4,
        goalsPer90: 0,
        xGPer90: 0.03,
        shotAccuracyPct: 22,
        conversionRatePct: 0,
        shotsOnTarget: 4,
        touchesInBox: 34,
        weakFootShotPct: 8,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 20,
        skillfulFootShotScore: 5.8,
        tacklesWonPct: 62,
        interceptions: 40,
        recoveries: 72,
        blocks: 26,
        aerialDuelsWonPct: 50,
        clearances: 54,
        physicalDuelsWonPct: 58,
        strengthDuels: 88,
        balance: 7.7,
        stamina: 8.4,
        bodyContactSuccessPct: 56,
      },
    },
    {
      clubKey: 'realMadrid' as const,
      id: 'madrid-bellingham-005',
      name: 'Jude Bellingham',
      birthDate: new Date('2003-06-29'),
      nationality: 'England',
      position: Position.CAM,
      photoUrl:
        'https://www.zerozero.com.ar/img/jogadores/new/75/32/737532_jude_bellingham_20250618231333.png',
      height: 1.86,
      weight: 75,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 5,
      contractStart: new Date('2023-07-01'),
      contractEnd: new Date('2029-06-30'),
      stats: {
        matchesPlayed: 35,
        minutesPlayed: 3050,
        goals: 19,
        assists: 9,
        yellowCards: 8,
        redCards: 0,
        dribblesAttempted: 96,
        dribbleSuccessPct: 61,
        progressiveCarries: 76,
        carriesIntoFinalThird: 64,
        ballRetentionPct: 85,
        foulsWon: 58,
        topSpeed: 32.2,
        sprintDistance: 1960,
        accelerations: 262,
        progressiveRuns: 74,
        distanceCovered: 10.55,
        passAccuracyPct: 86,
        progressivePasses: 70,
        keyPasses: 56,
        throughBalls: 14,
        crossAccuracyPct: 26,
        xA: 7.8,
        weakFootPassPct: 24,
        weakFootPassAccuracyPct: 80,
        progressiveWfPasses: 26,
        skillfulFootPassScore: 8.6,
        goalsPer90: 0.56,
        xGPer90: 0.45,
        shotAccuracyPct: 56,
        conversionRatePct: 22,
        shotsOnTarget: 58,
        touchesInBox: 168,
        weakFootShotPct: 20,
        weakFootGoals: 5,
        weakFootShotAccuracyPct: 50,
        skillfulFootShotScore: 8.4,
        tacklesWonPct: 56,
        interceptions: 38,
        recoveries: 86,
        blocks: 16,
        aerialDuelsWonPct: 56,
        clearances: 22,
        physicalDuelsWonPct: 62,
        strengthDuels: 98,
        balance: 8.5,
        stamina: 8.8,
        bodyContactSuccessPct: 58,
      },
    },
    {
      clubKey: 'realMadrid' as const,
      id: 'madrid-kroos-006',
      name: 'Toni Kroos',
      birthDate: new Date('1990-01-04'),
      nationality: 'Germany',
      position: Position.CM,
      photoUrl:
        'https://b.fssta.com/uploads/application/soccer/headshots/2252.png',
      height: 1.83,
      weight: 76,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 8,
      contractStart: new Date('2014-07-01'),
      contractEnd: new Date('2024-07-01'),
      stats: {
        matchesPlayed: 34,
        minutesPlayed: 2750,
        goals: 1,
        assists: 10,
        yellowCards: 4,
        redCards: 0,
        dribblesAttempted: 18,
        dribbleSuccessPct: 62,
        progressiveCarries: 22,
        carriesIntoFinalThird: 14,
        ballRetentionPct: 94,
        foulsWon: 12,
        topSpeed: 26.8,
        sprintDistance: 680,
        accelerations: 72,
        progressiveRuns: 22,
        distanceCovered: 9.25,
        passAccuracyPct: 94,
        progressivePasses: 78,
        keyPasses: 64,
        throughBalls: 22,
        crossAccuracyPct: 38,
        xA: 8.8,
        weakFootPassPct: 14,
        weakFootPassAccuracyPct: 88,
        progressiveWfPasses: 16,
        skillfulFootPassScore: 9.2,
        goalsPer90: 0.033,
        xGPer90: 0.04,
        shotAccuracyPct: 42,
        conversionRatePct: 8,
        shotsOnTarget: 12,
        touchesInBox: 48,
        weakFootShotPct: 8,
        weakFootGoals: 0,
        weakFootShotAccuracyPct: 28,
        skillfulFootShotScore: 6.8,
        tacklesWonPct: 48,
        interceptions: 36,
        recoveries: 68,
        blocks: 14,
        aerialDuelsWonPct: 52,
        clearances: 22,
        physicalDuelsWonPct: 50,
        strengthDuels: 72,
        balance: 7.5,
        stamina: 7.6,
        bodyContactSuccessPct: 48,
      },
    },
    {
      clubKey: 'realMadrid' as const,
      id: 'madrid-modric-007',
      name: 'Luka Modrić',
      birthDate: new Date('1985-09-09'),
      nationality: 'Croatia',
      position: Position.CM,
      photoUrl:
        'https://www.fifarosters.com/assets/players/fifa24/faces/177003.png',
      height: 1.72,
      weight: 66,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 10,
      contractStart: new Date('2012-08-01'),
      contractEnd: new Date('2024-06-30'),
      stats: {
        matchesPlayed: 32,
        minutesPlayed: 2280,
        goals: 2,
        assists: 7,
        yellowCards: 5,
        redCards: 0,
        dribblesAttempted: 54,
        dribbleSuccessPct: 64,
        progressiveCarries: 46,
        carriesIntoFinalThird: 40,
        ballRetentionPct: 91,
        foulsWon: 24,
        topSpeed: 27.5,
        sprintDistance: 880,
        accelerations: 112,
        progressiveRuns: 38,
        distanceCovered: 9.65,
        passAccuracyPct: 90,
        progressivePasses: 68,
        keyPasses: 58,
        throughBalls: 16,
        crossAccuracyPct: 32,
        xA: 6.5,
        weakFootPassPct: 22,
        weakFootPassAccuracyPct: 84,
        progressiveWfPasses: 20,
        skillfulFootPassScore: 9,
        goalsPer90: 0.079,
        xGPer90: 0.07,
        shotAccuracyPct: 48,
        conversionRatePct: 12,
        shotsOnTarget: 14,
        touchesInBox: 72,
        weakFootShotPct: 24,
        weakFootGoals: 1,
        weakFootShotAccuracyPct: 44,
        skillfulFootShotScore: 7.2,
        tacklesWonPct: 52,
        interceptions: 42,
        recoveries: 76,
        blocks: 14,
        aerialDuelsWonPct: 42,
        clearances: 16,
        physicalDuelsWonPct: 48,
        strengthDuels: 58,
        balance: 8.6,
        stamina: 7.9,
        bodyContactSuccessPct: 44,
      },
    },
    {
      clubKey: 'realMadrid' as const,
      id: 'madrid-camavinga-008',
      name: 'Eduardo Camavinga',
      birthDate: new Date('2002-11-10'),
      nationality: 'France',
      position: Position.CM,
      photoUrl:
        'https://cdn-img.staticzz.com/img/planteis/new/20/54/11532054_eduardo_camavinga_20240809101024.png',
      height: 1.82,
      weight: 75,
      preferredFoot: PreferredFoot.LEFT,
      shirtNumber: 12,
      contractStart: new Date('2021-08-01'),
      contractEnd: new Date('2029-06-30'),
      stats: {
        matchesPlayed: 34,
        minutesPlayed: 2480,
        goals: 2,
        assists: 5,
        yellowCards: 8,
        redCards: 0,
        dribblesAttempted: 82,
        dribbleSuccessPct: 60,
        progressiveCarries: 72,
        carriesIntoFinalThird: 54,
        ballRetentionPct: 84,
        foulsWon: 36,
        topSpeed: 31.2,
        sprintDistance: 1920,
        accelerations: 258,
        progressiveRuns: 64,
        distanceCovered: 10.35,
        passAccuracyPct: 88,
        progressivePasses: 58,
        keyPasses: 38,
        throughBalls: 9,
        crossAccuracyPct: 26,
        xA: 4.5,
        weakFootPassPct: 32,
        weakFootPassAccuracyPct: 76,
        progressiveWfPasses: 20,
        skillfulFootPassScore: 7.8,
        goalsPer90: 0.073,
        xGPer90: 0.06,
        shotAccuracyPct: 42,
        conversionRatePct: 11,
        shotsOnTarget: 14,
        touchesInBox: 62,
        weakFootShotPct: 18,
        weakFootGoals: 1,
        weakFootShotAccuracyPct: 38,
        skillfulFootShotScore: 6.9,
        tacklesWonPct: 62,
        interceptions: 46,
        recoveries: 92,
        blocks: 22,
        aerialDuelsWonPct: 48,
        clearances: 28,
        physicalDuelsWonPct: 60,
        strengthDuels: 94,
        balance: 8.3,
        stamina: 8.9,
        bodyContactSuccessPct: 56,
      },
    },
    {
      clubKey: 'realMadrid' as const,
      id: 'madrid-vinicius-009',
      name: 'Vinícius Júnior',
      birthDate: new Date('2000-07-12'),
      nationality: 'Brazil',
      position: Position.LW,
      photoUrl:
        'https://cdn-img.staticzz.com/img/jogadores/new/77/37/547737_vinicius_junior_20250923225603.png',
      height: 1.76,
      weight: 73,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 7,
      contractStart: new Date('2018-07-01'),
      contractEnd: new Date('2027-06-30'),
      stats: {
        matchesPlayed: 36,
        minutesPlayed: 2960,
        goals: 15,
        assists: 8,
        yellowCards: 10,
        redCards: 0,
        dribblesAttempted: 168,
        dribbleSuccessPct: 56,
        progressiveCarries: 92,
        carriesIntoFinalThird: 78,
        ballRetentionPct: 74,
        foulsWon: 92,
        topSpeed: 34.2,
        sprintDistance: 2520,
        accelerations: 348,
        progressiveRuns: 96,
        distanceCovered: 9.45,
        passAccuracyPct: 79,
        progressivePasses: 52,
        keyPasses: 58,
        throughBalls: 14,
        crossAccuracyPct: 28,
        xA: 8.5,
        weakFootPassPct: 34,
        weakFootPassAccuracyPct: 68,
        progressiveWfPasses: 26,
        skillfulFootPassScore: 8.4,
        goalsPer90: 0.46,
        xGPer90: 0.42,
        shotAccuracyPct: 54,
        conversionRatePct: 20,
        shotsOnTarget: 62,
        touchesInBox: 152,
        weakFootShotPct: 22,
        weakFootGoals: 4,
        weakFootShotAccuracyPct: 48,
        skillfulFootShotScore: 8.1,
        tacklesWonPct: 38,
        interceptions: 18,
        recoveries: 52,
        blocks: 8,
        aerialDuelsWonPct: 34,
        clearances: 10,
        physicalDuelsWonPct: 48,
        strengthDuels: 74,
        balance: 8.8,
        stamina: 8.6,
        bodyContactSuccessPct: 48,
      },
    },
    {
      clubKey: 'realMadrid' as const,
      id: 'madrid-rodrygo-010',
      name: 'Rodrygo',
      birthDate: new Date('2001-01-09'),
      nationality: 'Brazil',
      position: Position.RW,
      photoUrl: 'https://cdn.futwiz.com/assets/img/fc25/faces/243812.png',
      height: 1.74,
      weight: 64,
      preferredFoot: PreferredFoot.RIGHT,
      shirtNumber: 11,
      contractStart: new Date('2019-07-01'),
      contractEnd: new Date('2028-06-30'),
      stats: {
        matchesPlayed: 35,
        minutesPlayed: 2480,
        goals: 11,
        assists: 9,
        yellowCards: 4,
        redCards: 0,
        dribblesAttempted: 122,
        dribbleSuccessPct: 58,
        progressiveCarries: 78,
        carriesIntoFinalThird: 62,
        ballRetentionPct: 80,
        foulsWon: 44,
        topSpeed: 33.1,
        sprintDistance: 2200,
        accelerations: 302,
        progressiveRuns: 82,
        distanceCovered: 9.15,
        passAccuracyPct: 84,
        progressivePasses: 54,
        keyPasses: 50,
        throughBalls: 12,
        crossAccuracyPct: 34,
        xA: 7.6,
        weakFootPassPct: 28,
        weakFootPassAccuracyPct: 74,
        progressiveWfPasses: 23,
        skillfulFootPassScore: 8.2,
        goalsPer90: 0.4,
        xGPer90: 0.36,
        shotAccuracyPct: 54,
        conversionRatePct: 21,
        shotsOnTarget: 42,
        touchesInBox: 124,
        weakFootShotPct: 18,
        weakFootGoals: 3,
        weakFootShotAccuracyPct: 50,
        skillfulFootShotScore: 8,
        tacklesWonPct: 44,
        interceptions: 26,
        recoveries: 64,
        blocks: 12,
        aerialDuelsWonPct: 38,
        clearances: 12,
        physicalDuelsWonPct: 46,
        strengthDuels: 66,
        balance: 8.5,
        stamina: 8.3,
        bodyContactSuccessPct: 46,
      },
    },
  ];

  const playersData = playersSeed.map((p) => ({
    ...p,
    stats: withCardFrequencies(p.stats),
  }));

  for (const p of playersData) {
    const player = await prisma.player.upsert({
      where: { id: p.id },
      update: {},
      create: {
        id: p.id,
        name: p.name,
        birthDate: p.birthDate,
        nationality: p.nationality,
        position: p.position,
        photoUrl: p.photoUrl,
        height: p.height,
        weight: p.weight,
        preferredFoot: p.preferredFoot,
      },
    });

    const playerSeason = await prisma.playerSeason.upsert({
      where: {
        playerId_seasonId: { playerId: player.id, seasonId: season.id },
      },
      update: {},
      create: {
        playerId: player.id,
        seasonId: season.id,
        clubId: clubs[p.clubKey].id,
        shirtNumber: p.shirtNumber,
        contractStart: p.contractStart,
        contractEnd: p.contractEnd,
        stats: { create: p.stats },
      },
    });

    await prisma.playerActivity.createMany({
      data: [
        '2023-08-01',
        '2023-09-01',
        '2023-10-01',
        '2023-11-01',
        '2023-12-01',
        '2024-01-01',
        '2024-02-01',
        '2024-03-01',
        '2024-04-01',
        '2024-05-01',
      ].map((month) => ({
        playerSeasonId: playerSeason.id,
        monthDate: new Date(month),
        minutesPlayed: 180 + Math.floor(Math.random() * 160),
      })),
      skipDuplicates: true,
    });
  }

  console.log(
    '✅ Seed completed — 40 players (Boca, River, Barcelona, Real Madrid), 2023-2024',
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => await prisma.$disconnect());
